FROM node:24-slim

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4173

# Adding npm run build to ensure the app is able to load the env variables correctly within the container
CMD ["sh", "-c", "npm run build && npm run preview -- --host 0.0.0.0 --port 4173"]