# Nginx configuration file

# Define the number of worker processes 
worker_processes 1;

events {
  # Max number of simultaneous connections
  worker_connections 1024;
}

http {
  include mime.types;

  upstream auth_service {
    server auth-service;
  }

  # Define upstream for search service with load balancing
  # By default it uses round-robin method
  upstream search_service {
    # least_conn;  # Uncomment to use least connections method
    # ip_hash;    # Uncomment to use IP hash method
    # weight;     # Uncomment to use weighted round-robin method

    server search-service-1;
    server search-service-2;
    server search-service-3;
  }

  server {
    # Nginx Listen on port 80 for incoming HTTP requests
    listen 80;

    # "localhost/api/auth/" will be forwarded to auth_service
    location /api/auth {
      proxy_pass http://auth_service/auth;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # "localhost/api/search/" will be forwarded to search_service
    location /api/search {
      proxy_pass http://search_service/search;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
